#!/usr/bin/env bash

set -e


# Colors for Messages
GREEN=`tput setaf 2`
RED=`tput setaf 1`
MAGENTA=`tput setaf 5`
RST=`tput sgr0`

# Print some info to stdout
function info {
	echo "${GREEN}$@${RST}"
}

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
#CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_PLUGIN_DIR="dotbot_plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

#"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    info "!!! Starting configuration: ${conf}"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${BASEDIR}/${DOTBOT_PLUGIN_DIR}/dotbot-git" -c "${conf}${CONFIG_SUFFIX}"
done
