---
- name: Print no WSL msg
  debug:
    msg: "No WSL detected"

- name: Install no WSL packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - guake
    - urlview
    - xautomation

